### ISSUE TITLE
tiptoi_reveng jar is missing

### ISSUE THREAD

**Issue by anux-linux** [Martin-Dames/Tingeltangel#10]
I forked the Projekt and tried to build it. But it failed, because it could not import classes from tiptoi_reveng. Appereantly they are not there.

**Comment by jze** [comment]
The sources have to be generated first. When you run "mvn compile" it will happen automatically.

**Comment by anux-linux** [comment]
Ok solved the problem. When trying to runn "mvn compile" in eclipse, the source will not be generated. In netbeans everything is fine.
