### ISSUE TITLE
Is this Intention?

### ISSUE THREAD

**Issue by andretietz** [Martin-Dames/Tingeltangel#24]
Hey I am just refactoring a few things and I [found this line](https://github.com/Martin-Dames/Tingeltangel/blob/master/core/src/main/java/tingeltangel/core/IndexTableCalculator.java#L34)

```java
    public static int getPositionInFileFromCode(int code, int n) {
        if (((code & 255) != 0) | (n < 0)) {
            return -1;
        }
        ....
```
The first line of the method seems unintentionally beeing a `|` instead of an `||`. 
Or is this Intention?

**Comment by Martin-Dames** [comment]
In this special case it perhaps doesn't matter, but it should be ` || `. Can you include ths in you next pull request?

**Comment by andretietz** [comment]
fixing this in #26
