### ISSUE TITLE
Question: What is this table about?

### ISSUE THREAD

**Issue by andretietz** [Martin-Dames/Tingeltangel#25]
Hey Martin!

I've [rewritten parts in kotlin](https://github.com/andretietz/Tingeltangel/tree/feature/fullchange), due to it's simplicity, also trying to separate the project from eachother.

There's one point I am not understanding due to the lack of documentation. It's some [magic index map](https://github.com/Martin-Dames/Tingeltangel/blob/63fdbcf9b1e949eae4caf6237f60309ac8305616/core/src/main/java/tingeltangel/core/IndexTableCalculator.java#L24)

What is it about and how does it come together?

Small note:
Due to the fact that rust as a language becomes more interesting, I am trying to convert parts of the project into a rust project. (atm as private project, not public yet)

**Comment by Martin-Dames** [comment]
A german explanation can be found here:
https://www.ting-el-tangel.de/doku.php?id=dateiformat#die_ouf_datei
I have no clue why the ouf file format is that stupid and/or complex. I created these functions by data analysis, so it's possible that there is an easyer way to do the offset calculations.

**Comment by andretietz** [comment]
How do you come to this integer table?

This is what I mean:

```java
private final static int[] E = { 578, 562, 546, 530, 514, 498, 482, 466,
                                 322, 306, 290, 274, 258, 242, 226, 210, -446,
                                 -462, -478, -494, -510, -526, -542, -558, -702,
                                 -718, -734, -750, -766, -782, -798, -814};
```
