### ISSUE TITLE
Missing example book to start from

### ISSUE THREAD

**Issue by nichtich** [Martin-Dames/Tingeltangel#5]
I am running Tingeltangel on Ubuntu 15.10 from the latest developer version (524aa95). Trying to load or import a book from repository results in an empty list. There should be an indicator to show that books are expected to be located in `~/.tingeltangel/books/`, at least if the list is empty (no books found). The "empty" (?) book with ID 1500 does not contain anything useful. I recommend to include `Testbuch` (directory contained in this repository) as example. I was not able to open this book because it is only given as file `book.tbu` without source files (`.ouf`, `.txt`, `.src`).

**Comment by Martin-Dames** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hello Jakob,
the latest develpment version has many bugs. Thats one of them. The MID 15000 is not valid. You habe to create a new book from the menu.
If you want to USE the tool please download the latest version from
http://www.ting-el-tangel.de
I will release a new stabel version in a few weeks.
Best regards
Martin

Am 5. Januar 2016 20:59:54 MEZ, schrieb "Jakob Voß" <notifications@github.com>:
>I am running Tingeltangel on Ubuntu 15.10 from the latest developer
>version (524aa95). Trying to load or import a book from repository
>results in an empty list. There should be an indicator to show that
>books are expected to be located in `~/.tingeltangel/books/`, at least
>if the list is empty (no books found). The "empty" (?) book with ID
>1500 does not contain anything useful. I recommend to include
>`Testbuch` (directory contained in this repository) as example. I was
>not able to open this book because it is only given as file `book.tbu`
>without source files (`.ouf`, `.txt`, `.src`).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Martin-Dames/Tingeltangel/issues/5

- --
gpg keys: https://martin.bastionbytes.de/gpg

Diese #Email wurde von meiner #PDP-11 gesendet.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.1.1

iQJDBAEBCgAtBQJWjCWLJhxNYXJ0aW4gRGFtZXMgPG1hcnRpbkBiYXN0aW9uYnl0
ZXMuZGU+AAoJEIqKUUOO5mbkFjwQAJGYvLQ3XBLcaWPI1oVlylnExvBZgFahJ429
g2AGVhunFFG0JwDqdM8dOUVpOeqRCWQ4N+mSDff3hwbYXysl9OnOhpBMwlC/2zIs
IwtVcSJQQu0Lpn0IFQt4GjM0sZQP2UKRKqaSFGYmIj8pgY4QB1+NRxBRdPFqtUDU
Mq7ehIGzFH6IncESSGPXRDC2//5WZ2qJclxiyb907DQESMh+y9VewPMR3AqaTMEk
x8AWHpbYmj9NQhv7EeEkP17oekXrBzTMakt9nIFcLy/6I7o8HVR9QhOYsSVmIHnQ
clcHNR3d/utRj3sAj104v7zahhrTZaNhmtIO1+v7kXTD6FqZTClop0H4GjuJeKH0
c1djLq09n5iYUBHffUcVrEjWuN2tP4NmzgWk3BBrtRFQwx/uGwH+H42QMk97kZQS
tFtmha1nuY0Jc0oh+Y7S1yhKzLdf5/NmG/ZsOWSgBJ3tW37v73wfm7z/3Ohh76o3
PHdfikilXXQisCGQuevM4W1QXDdA5gRPz6eNsoywNF/O6jmhuIWFQfpV1Sy/fDon
6814CxMSxazxGe/bvHoitMPXTowwfi/zTf6BXRH7GTnvGE556rlVpEpnAFbfbyK2
OqoscclrQxijCFaN2pSi4O9e40EE3j/1sVIR2iaRN5hir1791KV35KGeCKGh5qIn
4vHTkr2j
=soya
-----END PGP SIGNATURE-----

**Comment by Martin-Dames** [comment]
I removed "Testbuch" because it used the old file format ".tbu" which is 
not longer supported.

The issues with the "Repository Manager" is now fixed. If your 
repository is broken please delete the folder "repository" and restart 
the tool.

The "MID 15000" bug is mostly an gui issue. I started to redesign some 
parts of the gui - so the bug will be resolved some day.

Best regards
Martin

**Comment by nichtich** [comment]
Thanks for fixing. I close this bug because once the repository manager works it is easy to get started with existing books.

Do you mind if I move the open issues from README.md to this GitHub issue tracker? Should I wait for another release before raising new bug reports and feature requests?
